// export enum FILTER_STATUS_ENUM {
//   ACTIVE = 'ACTIVE',
//   DISABLED = 'DISABLED',
// }

export enum DECORATION_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum DECORATION_CATEGORY_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum BANNER_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum EVENT_TYPE_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum VENDOR_GROUP_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum VENDOR_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum MATERIAL_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum VENUE_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum PAYMENT_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum VENUE_HALLS_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum TALENT_SERVICE_TYPE_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum TALENT_SERVICE_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum TALENT_PACKAGE_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum TESTIMONIAL_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum FACILITIES_STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}
